### ISSUE TITLE
Wrong colors displaying in color picker when the model value is empty

### ISSUE THREAD

**Issue by trimantra** [buberdds/angular-bootstrap-colorpicker#145]
Hi,

I have used many colorpicker instances on a single page. I have encountered an issue when we have a color selected in one picker and have another picker where there is no color selected.

Below is the image of the picker with a value.
![screenshot from 2017-03-28 12-35-17](https://cloud.githubusercontent.com/assets/8026925/24393549/2f77cb4e-13b6-11e7-90c5-0698f403166f.png)

Below is the image of the picker on the same page but with empty value and it gets displayed like this
![screenshot from 2017-03-28 12-57-03](https://cloud.githubusercontent.com/assets/8026925/24393597/514087ac-13b6-11e7-9aea-0ac2ba6b8d46.png)

I think that the picker should be initialised with empty value if the model value is empty and it should not use the values of the previously opened picker. Or there should be a way to set the default picker values when the model is empty string.

Please help me out with this.

**Comment by buberdds** [comment]
@trimantra can u bump to the latest 3.0.26 version and verify it is fixed now? thanks

**Comment by trimantra** [comment]
@buberdds 

Thanks for the reply but the issue doesn't seem to be fixed yet.

Initially it shows the pointer to the top right side (i.e towards the red color) for both the pickers when model values for both the pickers are empty. But after I change the color in the first picker. Opening other picker still shows the color that I selected in the first picker.

**Comment by buberdds** [comment]
Can you repro this issue using demo page http://codepen.io/buberdds/full/fBAsr/ ?

**Comment by trimantra** [comment]
Hi,

Thanks for the quick reply.
I was not able to reproduce the issue in the demo. May be there is some issue in my setup.

Thanks for your valuable time and support. I deeply appreciate that.

Thanks again.

**Comment by buberdds** [comment]
Well, just make just you're using v3.0.26.

**Comment by trimantra** [comment]
OK I have checked that. It works now.

I have also changed the library code to show the pointer on top left when there is no color in the model value.

Thanks a lot. :)

**Comment by buberdds** [comment]
cool, if you have time you can always create a PR to fix pointer alignment issue:) thanks!

**Comment by trimantra** [comment]
Hi,

I have created a pull request. Its #146 . Please check it when you have time.
